#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged --allow-empty
set CI=true && npm test
#npm test

# # #!/usr/bin/env sh
# . "$(dirname "$0")/h"

# # . "$(dirname -- "$0")/_/husky.sh"

# npx lint-staged --allow-empty
# set CI=true && npm test